import React from 'react';
import Link from 'next/link';
import { Wordmark } from '@/components/Common/Wordmark';
import { Footer } from '@/components/Common/Footer';

export const metadata = {
  title: 'Terms of Service & License — Fieldwork Studio',
  description:
    'Terms of service, open-source licensing provisions, acceptable use guidelines, and liability disclaimers for Fieldwork Studio.',
};

export default function TermsPage() {
  return (
    <div className="studio-root">
      {/* Top Header */}
      <header className="studio-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
          <Wordmark />
          <span className="badge badge-lime">Terms &amp; License</span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <Link href="/" className="btn primary" style={{ padding: '6px 14px', fontSize: '13px' }}>
            ← Back to Studio
          </Link>
        </div>
      </header>

      {/* Main Container */}
      <main className="studio-main" style={{ maxWidth: '860px', paddingBottom: '60px' }}>
        {/* Banner */}
        <section className="dashboard-banner animate-fade-in" style={{ marginBottom: '32px' }}>
          <div className="banner-sub">
            <span className="badge badge-lime">Open Source Terms</span>
            <span>·</span>
            <span>Effective: September 2026</span>
          </div>
          <h1>Terms of Service &amp; License</h1>
          <p className="tagline">
            Fieldwork is an open-source development planning tool built to provide self-reflection,
            workplace alignment, and actionable roadmaps.
          </p>
        </section>

        {/* Content Blocks */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {/* Section 1 */}
          <section className="hf-card">
            <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--white)' }}>
              1. Acceptance of Terms
            </h2>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6 }}>
              By accessing, browsing, or using Fieldwork Studio (the &ldquo;Application&rdquo;), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with these terms, please do not use the Application.
            </p>
          </section>

          {/* Section 2 */}
          <section className="hf-card">
            <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--white)' }}>
              2. Open Source License &amp; Intellectual Property
            </h2>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6 }}>
              The Fieldwork codebase, algorithms, and design implementation are created by Karthikeyan T (<code>@carthworks</code>) and licensed under the <strong>Apache License, Version 2.0</strong> (or MIT where specified).
            </p>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6, marginTop: '8px' }}>
              You are free to inspect, fork, modify, and distribute the software in accordance with open-source licensing conditions. The visual tokens and aesthetic architecture follow the Higgsfield design system.
            </p>
          </section>

          {/* Section 3 */}
          <section className="hf-card">
            <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--white)' }}>
              3. Nature of the Service &amp; Professional Advice Disclaimer
            </h2>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6 }}>
              The archetypes, generational analyses, trait scoring, and action roadmaps generated by Fieldwork are designed strictly for <strong>professional self-reflection, goal organization, and structured manager conversations</strong>.
            </p>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6, marginTop: '8px' }}>
              Fieldwork does not provide certified psychological, psychiatric, medical, legal, or licensed employment counsel. Ratings and outputs represent deterministic heuristics based on your inputs and should be applied using your own independent professional judgment.
            </p>
          </section>

          {/* Section 4 */}
          <section className="hf-card">
            <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--white)' }}>
              4. User Content &amp; Local Data Retention
            </h2>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6 }}>
              All data entered into Fieldwork belongs exclusively to you. Fieldwork maintains no remote databases or server-side logs of your entries. Because your data resides solely within your browser&rsquo;s local storage, you are responsible for maintaining any exported copies (via PDF or Markdown export) if you wish to preserve them across devices.
            </p>
          </section>

          {/* Section 5 */}
          <section className="hf-card">
            <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--white)' }}>
              5. Disclaimer of Warranties &amp; Limitation of Liability
            </h2>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6 }}>
              THE APPLICATION IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE AUTHORS AND CONTRIBUTORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE APPLICATION.
            </p>
          </section>

          {/* Section 6 */}
          <section className="hf-card">
            <h2 style={{ fontSize: '18px', marginBottom: '12px', color: 'var(--white)' }}>
              6. Governing Law &amp; Inquiries
            </h2>
            <p style={{ color: 'var(--white-a80)', fontSize: '14px', lineHeight: 1.6 }}>
              These Terms shall be interpreted and governed by applicable general principles of law without regard to conflict of law provisions. For any questions regarding terms, licensing, or commercial permissions, contact:
            </p>
            <div style={{ marginTop: '12px', display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '13.5px' }}>
              <div><strong>Author:</strong> Karthikeyan T (<code>@carthworks</code>)</div>
              <div><strong>GitHub Repository:</strong> <a href="https://github.com/carthworks" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--lime-100)' }}>https://github.com/carthworks</a></div>
              <div><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/carthworks" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--lime-100)' }}>https://www.linkedin.com/in/carthworks</a></div>
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
